### ISSUE TITLE
Лабораторная работа #4

### ISSUE THREAD

**Issue by Doshinsky** [Doshinsky/Lab-4#1]
Выполнили:
Дощинский Илья Владиславович
Копылова Елена Витальевна

@evgeny-p

**Comment by evgeny-p** [comment]
Работа сдается в неработоспособном состоянии.

1. См. [3.2 What Name to Give Your Makefile](http://www.gnu.org/software/make/manual/make.html#Makefile-Names)

  ```
  $ make
  make: *** No targets specified and no makefile found.  Stop.
  ```
1. После испрвления этой ошибки сборка все еще не будет выполняться из-за синтаксических ошибок в мейкфайле.

1. Выполнение `make clean` при отсутствии артефактов приводит к ошибке.

Замечания по коду:

1. В заголовочном файле отсутствуют `include guards`.
1. Функция `digit` вынесена в заголовочный файл, но фактически является внутренней деталью реализации алгоритма. Следовательно, она не предназначена для пользователя модуля.
1. `radix.c:12` лишний пробел в начале строки.
1. В строке 53 оператор присваивания не выделен пробелами.
1. Строки 54 и 55 этого же файла написаны с неконсистентными со всем остальным кодом отсутпами.
1. В строках 34, 49 и 54 отсутствует пробел после запятой.
1. Также скачут отступы некоторых комментариев.
1. То, что в комментариях называется memory leak, по факту таковым не является. Можем обсудить на занятии.
1. Во многих случаях, если Вы выделяете блок кода комментарием, есть вероятность, что этот фрагмент следует оформить как функцию. Также многие комментарии избыточны, т.к. поясняют *что* происходит. Это и так видно по коду.
1. Строку `functional.c:35` нужно разбить минимум на две.
1. В строке 41 отсутствует пробел перед фигурной скобкой.
1. В функции `radixsort` множество однобуквенных переменных. Им можно дать более осмысленные имена?
1. Неконсистентное именование переменных: часть имен написана в верхнем регистре.
1. С какой целью функция `radixsort` возвращает значение?
1. Имя исполняемого файла не соответствует назначению приложения.
1. Имя файла `functional.c` слишком общее.

**Comment by Doshinsky** [comment]
- Исправлены три пункта из-за которой проект был неработоспособным.

- > В заголовочном файле отсутствуют `include guards`.
К сожалению, не смог разобраться с данной конструкцией и подключить ее к своей программе.

- > Функция `digit` вынесена в заголовочный файл, но фактически является внутренней деталью реализации алгоритма. Следовательно, она не предназначена для пользователя модуля.
Данная функция используется для краткости, чтобы несколько раз не переписывать её внутри функции `radix`.

- пп. 3-7, 10, 11
Лишние пробелы убраны и по необходимости добавлены, отступы откалиброваны, строки разбиты. 

- > То, что в комментариях называется `memory leak`, по факту таковым не является. Можем обсудить на занятии.
Данную функцию мне посоветовал преподаватель по САОД'у, но с радостью бы выслушал более подробное объяснение.

- п. 9
Данные комментарии были сделаны специально, чтобы объяснять одногруппникам код и чтобы самому, не вчитываясь в него, понимать что за что отвечает. В новых коммитах данные комментарии были удалены.

- > В функции `radixsort` множество однобуквенных переменных. Им можно дать более осмысленные имена?
Данные переменные в большинстве являются счётчиками, поэтому осмысленное название, по-моему, необязательно.

- > Неконсистентное именование переменных: часть имен написана в верхнем регистре.
Простите, не совсем понял суть данного пункта.

- > С какой целью функция `radixsort` возвращает значение?
Компилятор, использованный мною, слишком привередливый к типу `void`, поэтому проще использовать `int`-функцию, нежели чем бороться со всеми Warning'ами.

- > Имя исполняемого файла не соответствует назначению приложения.
`Radix` вполне логичное, как мне кажется, название для программы которая сортирует входной массив, используя поразрядную сортировку (англ. Radix Sort).

- > Имя файла `functional.c` слишком общее.
В данный файл были вынесены практически все функции, необходимые для работы файла `radix.c`. Иными словами, туда был перемещен весь функционал программы.

**Comment by Doshinsky** [comment]
Upd.

- [ ] Добавлен `#include guards`.
- [ ] Функция `digit` была сделана, как внутренняя.
- [ ] Функция `radixsort` была объявлена как `void`.
- [ ] В файле `functional.c` названия массивов были перенесены в нижний регистр.
- [ ] В `Makefile` `functional` был переименован в `radix`

**Comment by evgeny-p** [comment]
Принято.

Я бы предложил такой рефакторинг.
Переименования:

1. `m` → `max_digits`
1. `v` → `array`
1. `k` → `RADIX`
1. `c` → `counters`
1. `b` → `result`

Разное:

1. Из цикла вынесена функция сортировки. Поразрядная сортировка есть последовательность вызовов некоторого алгоритма сортировки с измеряющимся ключом. Хочется, чтобы в коде это было отражено явно.
1. Постфиксные инкременты заменены префиксными.
1. Объявления некоторых переменных перенесены ближе к месту использования.
1. Убран цикл заполнения массива `counters` нулями. Если размер массива — константное выражение, то его можно инициализировать, что сокращает количество кода.

Результирующий код (некоторые строки опущены):

```c
#include <malloc.h>
#include <string.h>

#define RADIX 10

static
void counting_sort(uint32_t *array, int n, int digit_index, uint32_t *result) {
    int counters[RADIX] = {0};

    int i;

    for (i = 0; i < n; ++i) {
        const int d = digit(array[i], digit_index);
        ++counters[d];
    }

    int count = 0;

    for (i = 0; i < RADIX; ++i) {
        const int old_count = counters[i];
        counters[i] = count;
        count += old_count;
    }

    for (i = 0; i < n; ++i) {
        const int d = digit(array[i], digit_index);
        result[counters[d]] = array[i];
        ++counters[d];
    }
}

void radixsort(uint32_t *array, int n) {
    const int max_digits = 6;

    uint32_t *result = malloc(n * sizeof(uint32_t));

    int digit_index;

    for (digit_index = 1; digit_index <= max_digits; ++digit_index) {
        counting_sort(array, n, digit_index, result);
        memcpy(array, result, n * sizeof(uint32_t));
    }

    free(result);
}
```

На изменениях не настаиваю.
